### ISSUE TITLE
Exception handler

### ISSUE THREAD

**Issue by ldejanovic8120rn** [RAF-SI-2022/Banka-1-Backend#4]
Pogledati specifikaciju i dodati greske uz propratnu poruku u zavisnosti koja greska je u pitanju. Greske ce biti grupisane u okviru jednog paketa "exceptions" i bice im podesen status i dobijace propratnu poruku. Vec postoji primer u kodu, potrebno je pregledati i dodati greske gde fale

**Branch:** feature/user-exception-handler

**Comment by npantos17** [comment]
Da li bi treba da pravim i ExceptionHandler klasu ili samo proveravam koje bi sve greske mogle da se dese i dodam ih?

**Comment by ldejanovic8120rn** [comment]
Dodat je exception handler, pogledaj samo da li negde eventualno nedostaje neka greska, u smislu kada se rade neke provere/validacije da li se ispaljuju dobri izuzeci i da li negde nedostaje neka provera i da se ispali greska
